{% set version = "1.5.0" %}

package:
  name: astunparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astunparse/astunparse-{{ version }}.tar.gz
  sha256: 55df3c2a659d6cb6a9a9041c750a8232a9925523405a8dfeb891b92d45a589cd

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.6.1,<2.0

test:
  imports:
    - astunparse

about:
  home: https://github.com/simonpercivall/astunparse
  license: BSD 3-Clause, PSF 2
  license_file: LICENSE
  summary: An AST unparser for Python.
  description: |
    This is a factored out version of unparse found in the Python source
    distribution; under Demo/parser in Python 2 and under Tools/parser in
    Python 3.
  dev_url: https://github.com/simonpercivall/astunparse
  doc_url: http://astunparse.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
