{% set version = "1.6.2" %}

package:
  name: astunparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astunparse/astunparse-{{ version }}.tar.gz
  sha256: dab3e426715373fd76cd08bb1abe64b550f5aa494cf1e32384f26fd60961eb67

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.6.1,<2.0

test:
  imports:
    - astunparse

about:
  home: https://github.com/simonpercivall/astunparse
  license: BSD 3-Clause, PSF 2
  license_file: LICENSE
  summary: An AST unparser for Python.
  description: |
    This is a factored out version of unparse found in the Python source
    distribution; under Demo/parser in Python 2 and under Tools/parser in
    Python 3.
  dev_url: https://github.com/simonpercivall/astunparse
  doc_url: http://astunparse.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
    - hoechenberger
