travis:
  secure:
    BINSTAR_TOKEN: RmMKarXKZ8LmLon4HrxWRCoM6wzU3fsv16XYpuStyrBjoXmlIDhWEXbfVRyfPq3HuGzxSkQuw+cxxqJjjcILIUjFUbbxHsTv97iQNgHsPl4+rfWy5VrM4NCnvXdRFnwCO4HT+LSRSMNUSBz/inFEFrkcSiVyBEDSJcZhLqtfXObyX3mXKx/EuTlPQa0g3xPKGBZxDcLrdtVmxHT4DBuuJioZn5zHe9DjMZViFNGlCbim4pJX5SZsZjAkFAgD7xPFj1IlMBmn/cdMJzNCheeKYHMbvlPWSEW8iuGpsrqbnPuUolzB0OgWE1E99bzRLVbKqUnzVDtICVSTOInbFPwAbDl0jTmNxfOPhKYd5HNhCTYogPXtjg/o3BQ5QVa90YKvg4U5IYJwTX21XjTQqXeDsPFIYtLyY6OF4hQf8U8DOmDBOCF6RFGZVnbuDjW+lARijhh/l2ymts4YB5j+YWNHT+rvGMbPnsZ8N5xzqudyXxa/0CTtwbmluPEOv7qtsmThUaqPIOaVTlAP88C4+i3Puv8CdehDOGiE7gR1rLpRNT48ZKl7vk/3p339LPqtbvsBCO7uM4Ly/8ZDQPNcI5dALUAFHwXMkQj852CsCBXBv/DpT8vJMft4bdnNlO9Vb3EgsKBPwPQRmM5f3xVfu81ISTVkPTBlDSWtVKj2wvpOucU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
