travis:
  secure:
    BINSTAR_TOKEN: n+Xbi5jm7rRmqS6JNSMNsaz2OKJeGylY/sEA2SxBqhvVCxegI+EBWRmIk+CkiZH7GlGCoZqcYR2rTOJVeNXd2XM35Ev5OHYMmxYR+cViCg/jURPt//MT5cL3QPtxzgGdfnRP7VU+BeMrNIYhkG5exJ/3xUYfgybpFlTUQbRNeaDAu2/ATGp2DrBoUIa3riGROFh0mNWFWXRcyFpP02qg2/JCovhDEznjOImIe28UF6SlwJd6CNf7F2Lf5d6rBRSe2ZhR7HGv17yj+q3Q7HkQJk3P/QEX131E7nXcKwYXXss0w4czqvGouJK3/guNygU/8H4Z2uj/h/d37pFLhJWJ9E/+ufyvdONK3UQdURSGLHGi37VT8AWKxG1jnsaJT//X3Lnl/4gPzEVqY572VrENxZ8zjZZgs4uetJCTCvhxgrkLMrWPhgSF4SJi3u60Kgmv5Bj7m1za4Q/ByfoMtpJ9YzME4VgwBVdZQHZd2ggZUzjONYadhUNcoAT5wtWZRdfREonomxLhshVKxcCsfQMJWc/k6qtVnl7vixyndtLv/cgI0xqFPloTqwhAAqo4WuliaHJ96FTh+6NYOXXTONl1k/7uE7AtuKRMb1AwU4jPGm8nwzB8AizcFMPIL3NhIIyjifT+/pK3gPW1sgDAM9ILWc9kRv+6DxkCXL6dIejcl8M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
